## Provide source and dependencies ##
FROM golang:alpine AS source
RUN go install github.com/goreleaser/goreleaser@latest && \
go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest

## Create container image ##
FROM golang:alpine as publish
COPY --from=source /go/bin/goreleaser /usr/local/bin/goreleaser
COPY --from=source /go/bin/nfpm /usr/local/bin/nfpm
RUN apk --no-cache add git